#line 2 "lexer.c"

#line 4 "lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 91
#define YY_END_OF_BUFFER 92
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[413] =
    {   0,
        0,    0,    0,    0,   92,   90,    2,    1,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   81,   79,   84,
       84,   84,   83,   84,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   84,   87,   89,   88,    2,   11,   18,
       12,   21,   15,    6,   17,    7,   24,   82,   85,    0,
       16,   82,   81,    0,    0,   81,    0,   79,   79,    4,
        8,   10,    9,    5,   83,   22,   14,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       29,   83,   83,   83,   83,   83,   25,   83,   55,   83,

       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   23,   13,   87,   86,    0,   82,
       82,   82,    0,    3,    0,   82,    0,   80,   19,   20,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   31,   83,
       83,   83,   77,   83,   83,   83,   83,   83,   83,   56,
       83,   83,   83,   83,   83,   83,   83,   76,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,    0,   82,   82,   82,   82,    0,    0,

        0,   80,   83,   83,   83,   83,   33,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   26,   83,   49,   83,
       83,   83,   83,   83,   83,   61,   77,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   76,   76,   76,   76,
       76,   76,   83,   83,   83,   83,   83,   83,   83,   78,
       83,   83,   83,   83,    0,    0,   82,   83,   83,   27,
       83,   83,   65,   83,   38,   83,   83,   83,   83,   63,
       83,   57,   83,   83,   83,   83,   83,   52,   83,   83,
       83,   83,   83,   83,   76,   76,   76,   76,   76,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   30,   83,

        0,   82,   82,   82,   82,   83,   83,   40,   83,   83,
       83,   83,   83,   83,   83,   47,   77,   83,   83,   83,
       83,   68,   83,   83,   35,   76,   76,   76,   76,   76,
       53,   83,   41,   50,   36,   83,   32,   83,   83,   83,
       82,   82,   82,   67,   83,   83,   83,   83,   34,   60,
       83,   83,   62,   83,   59,   83,   69,   83,   83,   76,
       76,   76,   76,   76,   70,   83,   39,   83,   83,   83,
       48,   42,   28,   83,   83,   83,   83,   45,   44,   76,
       75,   76,   76,   76,   83,   43,   83,   37,   83,   58,
       83,   64,   72,   76,   76,   76,   83,   46,   83,   83,

       76,   76,   74,   54,   66,   83,   73,   76,   83,   71,
       51,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    1,    1,    5,    6,    1,    7,
        7,    8,    9,    7,   10,   11,   12,   13,   14,   15,
       15,   15,   14,   14,   14,   16,   16,    7,    7,   17,
       18,   19,    7,    1,   20,   20,   21,   20,   22,   23,
       24,   24,   24,   24,   24,   25,   26,   24,   24,   27,
       24,   24,   24,   28,   29,   24,   24,   30,   24,   24,
        7,    1,    7,   31,   32,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   24,   42,   43,   44,   45,
       46,   47,   24,   48,   49,   50,   51,   52,   53,   54,
       55,   24,    7,   56,    7,    7,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[57] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    2,    1,    1,
        3,    1,    4,    4,    4,    4,    1,    1,    1,    4,
        4,    4,    4,    5,    5,    5,    5,    5,    5,    5,
        1,    5,    4,    4,    4,    4,    4,    4,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    1
    } ;

static const flex_int16_t yy_base[420] =
    {   0,
        0,    0,   54,   55,  552,  553,  549,  553,  532,  531,
       53,  553,  530,   51,   54,   52,   62,   70,  114,   58,
      529,   59,    0,   64,   29,   42,   65,   60,  503,   70,
      504,   88,   63,   54,  498,  492,   72,   82,  102,  494,
       69,  101,  101,  100,    0,  553,  529,  538,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  153,  553,  536,
      553,    0,   85,  148,  173,  553,  527,    0,  553,  519,
      553,  553,  553,  518,    0,  553,  553,  501,  484,  487,
      495,  493,  493,  480,  483,  494,  105,  488,  476,  491,
      472,  473,  478,  111,  472,  480,    0,  475,  108,  462,

      463,  465,  478,  466,  462,  461,  136,  476,  148,  477,
      464,  459,  473,  459,  456,  469,  461,  450,  455,  458,
      463,  131,  456,  455,  553,  553,    0,  553,  190,  553,
      472,  456,  490,  553,  179,  194,    0,  191,  553,  553,
      451,  443,  447,  456,  450,  450,  436,  436,  447,  437,
      130,  449,  446,  446,  442,  429,  427,  443,    0,  435,
      423,  422,    0,  439,  425,  423,  454,  427,  430,    0,
      431,  430,  412,  420,  426,  411,  409,  200,  412,  425,
      409,  410,  404,  406,  403,  415,  401,  412,  434,  412,
      414,  403,  395,  198,  220,  553,  421,  405,  197,  202,

      237,  553,  405,  400,  398,  402,    0,  390,  388,  388,
      387,  384,  392,  381,  398,  387,    0,  392,    0,  378,
      380,  382,  375,  376,  372,    0,  368,  370,  372,  379,
      377,  384,  375,  369,  366,  365,    0,  379,  370,  377,
      361,  371,  364,  356,  368,  354,  368,  356,  366,    0,
      354,  349,  361,  360,  246,  251,  255,  351,  361,    0,
      346,  347,    0,  355,    0,  346,  347,  341,  351,    0,
      346,    0,  345,  335,  369,  339,  333,    0,  332,  330,
      344,  333,  336,  331,  331,  335,  323,  331,  317,  333,
      334,  332,  327,  316,  314,  324,  315,  321,    0,  315,

      259,  269,  553,  337,  321,  308,  306,    0,  315,  310,
      303,  303,  316,  306,  317,    0,    0,  302,  301,  240,
      310,    0,  303,  310,    0,  307,  303,  305,  297,  290,
        0,  299,    0,    0,    0,  288,    0,  293,  293,  290,
      553,  311,  283,    0,  261,  274,  259,  271,    0,    0,
      273,  260,    0,  267,    0,  257,    0,  247,  251,  252,
      249,  249,  255,  244,    0,  250,    0,  253,  246,  251,
        0,    0,    0,  242,  236,  244,  231,    0,    0,  224,
        0,  213,  198,  193,  195,    0,  184,    0,  196,    0,
      180,    0,    0,  190,  181,  179,  178,    0,  164,  143,

      128,   82,    0,    0,    0,   70,    0,   80,   52,    0,
        0,  553,  312,  314,  319,  324,  327,   57,  328
    } ;

static const flex_int16_t yy_def[420] =
    {   0,
      412,    1,  413,  413,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  414,  412,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  412,  415,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  416,
      412,   58,   18,  412,  412,  412,  417,   19,  412,  412,
      412,  412,  412,  412,  414,  412,  412,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,

      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  412,  412,  415,  412,  412,  412,
      412,  412,  416,  412,  412,  412,  418,  417,  412,  412,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  419,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  412,  412,  412,  412,  412,  418,  418,

      412,  412,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  419,  419,  419,  419,
      419,  419,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  412,  412,  412,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  419,  419,  419,  419,  419,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,

      412,  412,  412,  412,  412,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  419,  419,  419,  419,  419,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  414,
      412,  412,  412,  414,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  419,
      419,  419,  419,  419,  414,  414,  414,  414,  414,  414,
      414,  414,  414,  414,  414,  414,  414,  414,  414,  419,
      419,  419,  419,  419,  414,  414,  414,  414,  414,  414,
      414,  414,  419,  419,  419,  419,  414,  414,  414,  414,

      419,  419,  419,  414,  414,  414,  419,  419,  414,  419,
      414,    0,  412,  412,  412,  412,  412,  412,  412
    } ;

static const flex_int16_t yy_nxt[610] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   19,   19,   20,   21,   22,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       24,    6,   25,   26,   27,   28,   29,   30,   23,   31,
       32,   23,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   23,   23,   44,   46,   46,   51,   54,
      199,   47,   47,   56,   58,   58,   58,   58,   55,   59,
       52,   57,   78,   60,   70,   71,   73,   74,   79,   61,
       62,   76,   63,   63,   63,   64,  102,   80,  411,   81,
      103,   65,   82,   83,   77,  100,   88,   84,   66,   67,

       89,   85,   93,   90,  106,   91,   65,   86,  101,  119,
       87,   83,   94,  120,  412,   95,  410,  125,  109,  107,
       66,  409,  108,   67,   62,   97,   68,   68,   68,   68,
       98,  110,   99,  408,  111,   65,  112,  121,  412,   83,
      123,  113,   69,  157,  149,  114,  122,  150,  124,  151,
       65,  115,  116,  162,  117,  126,  158,  163,   62,  164,
       64,   64,   64,   64,   69,   58,   58,   58,   58,   65,
      407,  190,  172,  191,  129,  130,  173,  131,  212,  213,
      175,  135,  135,  406,   65,  136,  136,  136,  136,  129,
      130,  136,  136,  136,  136,  132,  176,  177,  194,  194,

      405,  200,  195,  195,  195,  195,  136,  136,  136,  136,
      195,  195,  195,  195,  404,  403,  196,  201,  197,  202,
      238,  402,  401,  255,  239,  240,  241,  242,  255,  400,
      399,  196,  195,  195,  195,  195,  198,  201,  398,  397,
      396,  202,  130,  255,  131,  256,  256,  395,  255,  257,
      257,  257,  257,  394,  301,  301,  393,  130,  302,  302,
      302,  302,  132,  257,  257,  257,  257,  257,  257,  257,
      257,  302,  302,  302,  302,  392,  355,  303,  391,  304,
      356,  302,  302,  302,  302,  390,  389,  388,  387,  386,
      385,  341,  303,  342,  384,  383,  382,  305,  381,  380,

      379,  378,  377,  376,  375,  374,  341,  373,  372,  371,
      370,  343,   45,   45,   45,   45,   45,   75,   75,  127,
      341,  127,  127,  127,  133,  133,  133,  133,  133,  138,
      138,  237,  237,  341,  369,  368,  367,  366,  365,  364,
      363,  362,  361,  360,  359,  358,  357,  354,  353,  352,
      351,  350,  349,  348,  347,  346,  345,  344,  303,  303,
      340,  339,  338,  337,  336,  335,  334,  333,  332,  331,
      330,  329,  328,  327,  326,  325,  324,  323,  322,  321,
      320,  319,  318,  317,  316,  315,  314,  163,  313,  312,
      311,  310,  309,  308,  307,  306,  300,  299,  298,  297,

      296,  295,  294,  293,  292,  291,  290,  289,  288,  287,
      286,  285,  284,  283,  282,  281,  280,  279,  278,  277,
      276,  275,  274,  273,  272,  271,  270,  163,  250,  269,
      268,  267,  266,  265,  163,  264,  263,  262,  261,  260,
      259,  258,  196,  196,  254,  253,  252,  163,  163,  251,
      163,  250,  249,  248,  247,  246,  245,  244,  243,  236,
      235,  234,  233,  232,  231,  230,  229,  228,  227,  226,
      225,  224,  223,  222,  221,  220,  219,  218,  217,  216,
      215,  214,  211,  210,  209,  208,  207,  206,  205,  163,
      204,  203,  134,  130,  130,  193,  192,  189,  188,  187,

      186,  185,  184,  183,  182,  181,  180,  179,  178,  174,
      171,  170,  169,  168,  167,  166,  165,  161,  160,  159,
      156,  155,  154,  102,  153,  152,  148,  147,  146,  121,
      145,  144,  143,  142,  141,  140,  139,  137,  134,   48,
      128,  118,  105,  104,   96,   92,   72,   53,   50,   49,
       48,  412,    5,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,

      412,  412,  412,  412,  412,  412,  412,  412,  412
    } ;

static const flex_int16_t yy_chk[610] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    4,   11,   14,
      418,    3,    4,   15,   16,   16,   16,   16,   14,   17,
       11,   15,   25,   17,   20,   20,   22,   22,   25,   17,
       18,   24,   18,   18,   18,   18,   34,   26,  409,   26,
       34,   18,   26,   26,   24,   33,   28,   27,   18,   18,

       28,   27,   30,   28,   37,   28,   18,   27,   33,   41,
       27,   28,   30,   41,   63,   30,  408,   44,   38,   37,
       18,  406,   37,   18,   19,   32,   19,   19,   19,   19,
       32,   38,   32,  402,   39,   19,   39,   42,   63,   32,
       43,   39,   19,   94,   87,   39,   42,   87,   43,   87,
       19,   39,   39,   99,   39,   44,   94,   99,   64,   99,
       64,   64,   64,   64,   19,   58,   58,   58,   58,   64,
      401,  122,  107,  122,   58,   58,  107,   58,  151,  151,
      109,   65,   65,  400,   64,   65,   65,   65,   65,   58,
       58,  135,  135,  135,  135,   58,  109,  109,  129,  129,

      399,  138,  129,  129,  129,  129,  136,  136,  136,  136,
      194,  194,  194,  194,  397,  396,  136,  138,  136,  138,
      178,  395,  394,  199,  178,  178,  178,  178,  200,  391,
      389,  136,  195,  195,  195,  195,  136,  138,  387,  385,
      384,  138,  195,  199,  195,  201,  201,  383,  200,  201,
      201,  201,  201,  382,  255,  255,  380,  195,  255,  255,
      255,  255,  195,  256,  256,  256,  256,  257,  257,  257,
      257,  301,  301,  301,  301,  377,  320,  257,  376,  257,
      320,  302,  302,  302,  302,  375,  374,  370,  369,  368,
      366,  302,  257,  302,  364,  363,  362,  257,  361,  360,

      359,  358,  356,  354,  352,  351,  302,  348,  347,  346,
      345,  302,  413,  413,  413,  413,  413,  414,  414,  415,
      343,  415,  415,  415,  416,  416,  416,  416,  416,  417,
      417,  419,  419,  342,  340,  339,  338,  336,  332,  330,
      329,  328,  327,  326,  324,  323,  321,  319,  318,  315,
      314,  313,  312,  311,  310,  309,  307,  306,  305,  304,
      300,  298,  297,  296,  295,  294,  293,  292,  291,  290,
      289,  288,  287,  286,  285,  284,  283,  282,  281,  280,
      279,  277,  276,  275,  274,  273,  271,  269,  268,  267,
      266,  264,  262,  261,  259,  258,  254,  253,  252,  251,

      249,  248,  247,  246,  245,  244,  243,  242,  241,  240,
      239,  238,  236,  235,  234,  233,  232,  231,  230,  229,
      228,  227,  225,  224,  223,  222,  221,  220,  218,  216,
      215,  214,  213,  212,  211,  210,  209,  208,  206,  205,
      204,  203,  198,  197,  193,  192,  191,  190,  189,  188,
      187,  186,  185,  184,  183,  182,  181,  180,  179,  177,
      176,  175,  174,  173,  172,  171,  169,  168,  167,  166,
      165,  164,  162,  161,  160,  158,  157,  156,  155,  154,
      153,  152,  150,  149,  148,  147,  146,  145,  144,  143,
      142,  141,  133,  132,  131,  124,  123,  121,  120,  119,

      118,  117,  116,  115,  114,  113,  112,  111,  110,  108,
      106,  105,  104,  103,  102,  101,  100,   98,   96,   95,
       93,   92,   91,   90,   89,   88,   86,   85,   84,   83,
       82,   81,   80,   79,   78,   74,   70,   67,   60,   48,
       47,   40,   36,   35,   31,   29,   21,   13,   10,    9,
        7,    5,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,

      412,  412,  412,  412,  412,  412,  412,  412,  412
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.lex"
/* Marius-Mihail Gurgu 453084, Wei-Heng Ke 454447, Tamil Selvi Pandiyan 0453060 */
#define YY_NO_INPUT 1

#line 6 "lexer.lex"

#include <stdio.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>

// Global variable for the line number
int line_number = 1;

// If we're using bison (2nd assignment), include the generated header.
// Otherwise, manually define a couple of things that bison would usually
// handle for us.
#ifdef FOR_PARSER
# include "parser.h"
#else

// Declare type for semantic value
typedef union {
    bool bval;
    int ival;
    double fval;
    char *str;
} lex_val;
lex_val yylval;


// Declare tokens
#define TOKENS \
 X(BOOL) \
 X(INT) \
 X(FLOAT) \
 X(TYPE) \
 X(STATE) \
 X(IDENTIFIER) \
 X(ERROR) \
 X(BREAK) \
 X(CONTINUE) \
 X(DO) \
 X(FOR) \
 X(WHILE) \
 X(SWITCH) \
 X(CASE) \
 X(DEFAULT) \
 X(IF) \
 X(ELSE) \
 X(RETURN) \
 X(STRUCT) \
 X(ATTRIBUTE) \
 X(CONST) \
 X(UNIFORM) \
 X(VARYING) \
 X(BUFFER) \
 X(SHARED) \
 X(COHERENT) \
 X(VOLATILE) \
 X(RESTRICT) \
 X(READONLY) \
 X(WRITEONLY) \
 X(LAYOUT) \
 X(CENTROID) \
 X(FLAT) \
 X(SMOOTH) \
 X(NOPERSPECTIVE) \
 X(PATCH) \
 X(SAMPLE) \
 X(SUBROUTINE) \
 X(IN) \
 X(OUT) \
 X(INOUT) \
 X(INVARIANT) \
 X(PRECISE) \
 X(DISCARD) \
 X(LOWP) \
 X(MEDIUMP) \
 X(HIGHP) \
 X(PRECISION) \
 X(CLASS) \
 X(ILLUMINANCE) \
 X(AMBIENT) \
 X(PUBLIC) \
 X(PRIVATE) \
 X(SCRATCH) \
 X(RT_PRIMITIVE) \
 X(RT_CAMERA) \
 X(RT_MATERIAL) \
 X(RT_TEXTURE) \
 X(RT_LIGHT) \
 X(LEFT_OP) \
 X(RIGHT_OP) \
 X(INC_OP) \
 X(DEC_OP) \
 X(LE_OP) \
 X(GE_OP) \
 X(EQ_OP) \
 X(NE_OP) \
 X(AND_OP) \
 X(OR_OP) \
 X(XOR_OP) \
 X(MUL_ASSIGN) \
 X(DIV_ASSIGN) \
 X(ADD_ASSIGN) \
 X(MOD_ASSIGN) \
 X(LEFT_ASSIGN) \
 X(RIGHT_ASSIGN) \
 X(AND_ASSIGN) \
 X(XOR_ASSIGN) \
 X(OR_ASSIGN) \
 X(SUB_ASSIGN)

enum {
    _MAXCHAR = 255,
#define X(token) token,
    TOKENS
#undef X
} token;

#endif /* FOR_PARSER */

#line 839 "lexer.c"
#line 127 "lexer.lex"
 /* TODO Helper definitions here  */
 /* Regular Expressions Definitions */
 /*The following regex were imported from the flex manual, see https://westes.github.io/flex/manual/Numbers.html#Numbers */
#line 844 "lexer.c"

#define INITIAL 0
#define IN_COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 164 "lexer.lex"


 /* TODO Implement the rest... */

#line 1065 "lexer.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 413 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 553 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 168 "lexer.lex"
{line_number++;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 169 "lexer.lex"
{/* do nothing bby */}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 171 "lexer.lex"
{line_number++;} //single line comment 
	YY_BREAK
/* Operators */
case 4:
YY_RULE_SETUP
#line 175 "lexer.lex"
return LEFT_OP;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 176 "lexer.lex"
return RIGHT_OP;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 177 "lexer.lex"
return INC_OP;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 178 "lexer.lex"
return DEC_OP;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 179 "lexer.lex"
return LE_OP;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 180 "lexer.lex"
return GE_OP;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 181 "lexer.lex"
return EQ_OP;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 182 "lexer.lex"
return NE_OP;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 183 "lexer.lex"
return AND_OP;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 184 "lexer.lex"
return OR_OP;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 185 "lexer.lex"
return XOR_OP;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 186 "lexer.lex"
return MUL_ASSIGN;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 187 "lexer.lex"
return DIV_ASSIGN;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 188 "lexer.lex"
return ADD_ASSIGN;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 189 "lexer.lex"
return MOD_ASSIGN;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 190 "lexer.lex"
return LEFT_ASSIGN;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 191 "lexer.lex"
return RIGHT_ASSIGN;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 192 "lexer.lex"
return AND_ASSIGN;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 193 "lexer.lex"
return XOR_ASSIGN;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 194 "lexer.lex"
return OR_ASSIGN;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 195 "lexer.lex"
return SUB_ASSIGN;
	YY_BREAK
/* C Keywords */
case 25:
YY_RULE_SETUP
#line 198 "lexer.lex"
return IF;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 199 "lexer.lex"
return ELSE;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 200 "lexer.lex"
return BREAK;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 201 "lexer.lex"
return CONTINUE;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 202 "lexer.lex"
return DO;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 203 "lexer.lex"
return WHILE;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 204 "lexer.lex"
return FOR;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 205 "lexer.lex"
return SWITCH;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 206 "lexer.lex"
return CASE;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 207 "lexer.lex"
return DEFAULT;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 208 "lexer.lex"
return RETURN;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 209 "lexer.lex"
return STRUCT;
	YY_BREAK
/* GLSL keywords */
case 37:
YY_RULE_SETUP
#line 212 "lexer.lex"
return ATTRIBUTE;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 213 "lexer.lex"
return CONST;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 214 "lexer.lex"
return UNIFORM;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 215 "lexer.lex"
return BUFFER;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 216 "lexer.lex"
return SHARED;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 217 "lexer.lex"
return COHERENT;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 218 "lexer.lex"
return VOLATILE;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 219 "lexer.lex"
return RESTRICT;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 220 "lexer.lex"
return READONLY;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 221 "lexer.lex"
return WRITEONLY;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 222 "lexer.lex"
return LAYOUT;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 223 "lexer.lex"
return CENTROID;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 224 "lexer.lex"
return FLAT;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 225 "lexer.lex"
return SMOOTH;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 226 "lexer.lex"
return NOPERSPECTIVE;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 227 "lexer.lex"
return PATCH;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 228 "lexer.lex"
return SAMPLE;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 229 "lexer.lex"
return SUBROUTINE;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 230 "lexer.lex"
return IN;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 231 "lexer.lex"
return OUT;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 232 "lexer.lex"
return INOUT;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 233 "lexer.lex"
return INVARIANT;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 234 "lexer.lex"
return PRECISE;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 235 "lexer.lex"
return DISCARD;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 236 "lexer.lex"
return LOWP;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 237 "lexer.lex"
return MEDIUMP;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 238 "lexer.lex"
return HIGHP;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 239 "lexer.lex"
return PRECISION;
	YY_BREAK
/* RTSL keywords */
case 65:
YY_RULE_SETUP
#line 243 "lexer.lex"
return CLASS;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 244 "lexer.lex"
return ILLUMINANCE;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 245 "lexer.lex"
return AMBIENT;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 246 "lexer.lex"
return PUBLIC;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 247 "lexer.lex"
return PRIVATE;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 248 "lexer.lex"
return SCRATCH;
	YY_BREAK
/* RTSL interface types */
case 71:
YY_RULE_SETUP
#line 252 "lexer.lex"
return RT_PRIMITIVE;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 253 "lexer.lex"
return RT_CAMERA;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 254 "lexer.lex"
return RT_MATERIAL;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 255 "lexer.lex"
return RT_TEXTURE;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 256 "lexer.lex"
return RT_LIGHT;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 258 "lexer.lex"
{ yylval.str = strdup(yytext); return STATE; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 259 "lexer.lex"
{ yylval.str = strdup(yytext); return TYPE; } 
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 260 "lexer.lex"
{
	  char *string = strdup(yytext); 
	  if (strcmp(string, "true") == 0) yylval.bval = 1;
	  else if (strcmp(string, "false") == 0) yylval.bval = 0;
	  return BOOL; 
	} 
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 266 "lexer.lex"
{ yylval.ival = atoi(yytext); return INT; }	
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 267 "lexer.lex"
{ yylval.ival = (int)strtol(yytext, NULL, 0); return INT; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 268 "lexer.lex"
{ yylval.ival = (int)strtol(yytext, NULL, 0); return INT; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 269 "lexer.lex"
{ yylval.fval = atof(yytext); return FLOAT; } 
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 270 "lexer.lex"
{ yylval.str = strdup(yytext); return IDENTIFIER; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 271 "lexer.lex"
{yylval.str = strdup(yytext); return (int) yylval.str[0]; } //you have to put this after IDENTIFIER, dunno why yet;otherwise single-letter identifier will be seen as unary operators, long live empiricism aka 'if it works, it works'
	YY_BREAK
/* Takes care of multiline comments, see 'How can I match C-style comments?' in flex manual aka RTFM, see https://westes.github.io/flex/manual/How-can-I-match-C_002dstyle-comments_003f.html#How-can-I-match-C_002dstyle-comments_003f */

case 85:
YY_RULE_SETUP
#line 277 "lexer.lex"
BEGIN(IN_COMMENT);
	YY_BREAK


case 86:
YY_RULE_SETUP
#line 280 "lexer.lex"
BEGIN(INITIAL);
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 281 "lexer.lex"
// eat comment in chunks
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 282 "lexer.lex"
// eat the lone star
	YY_BREAK
case 89:
/* rule 89 can match eol */
YY_RULE_SETUP
#line 283 "lexer.lex"
line_number++;
	YY_BREAK

/* error situation */
case 90:
YY_RULE_SETUP
#line 289 "lexer.lex"
{ yylval.str = strdup(yytext); return ERROR; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 291 "lexer.lex"
ECHO;
	YY_BREAK
#line 1596 "lexer.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IN_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 413 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 413 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 412);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 291 "lexer.lex"


// Generate main code only for standalone compilation,
// but not if we're using bison (2nd assignment)
#ifndef FOR_PARSER
static const char *token_name(int token) {
    switch (token) {
#define X(token) \
        case token: \
            return #token;
TOKENS
#undef X
    }
    return NULL;
}

int main(int argc, char **argv) {
    if (argc > 1) {
        yyin = fopen(argv[1], "r");
		if (!yyin) {
			printf("File %s not found.\n", argv[1]);
			return 1;
		}
    } else {
        yyin = stdin;
    }

    int token;
    while ((token = yylex())) {
		printf("Line%3d:    ", line_number);
        if (token < 256) {
            printf("\"%c\"\n", token);
        } else {
            const char *name = token_name(token);
            if (!name) {
                printf("???\n");
            } else {
                switch (token) {
                    default:
                        printf("%s\n", name);
                        break;
                    case BOOL:
                        printf("%s [%s]\n", name, yylval.bval ? "true" : "false");
                        break;
                    case INT:
                        printf("%s [%d]\n", name, yylval.ival);
                        break;
                    case FLOAT:
                        printf("%s [%f]\n", name, yylval.fval);
                        break;
                    case TYPE:
                    case STATE:
                    case IDENTIFIER:
                    case ERROR:
                        printf("%s [%s]\n", name, yylval.str);
                        free(yylval.str);
                        break;
                }
            }
        }
    }

    return 0;
}
#endif /* FOR_PARSER */

